services:
  - type: web
    name: task-manager-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
